import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css";
import Provider from './provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '🕒TimeZone Converter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <section className="mb-10 py-2">
            {children}
          </section>
          <ToastContainer
            autoClose={5000}
            hideProgressBar={false}
            closeOnClick={true}
            pauseOnHover={true}
            draggable={true}
            rtl={false}
            pauseOnFocusLoss={true}
            theme='dark'
          />
        </Provider>
      </body>
    </html>
  )
}
